### ISSUE TITLE
frontier-squid requests unnecessary ephemeral-storage when PVCs are used

### ISSUE THREAD

**Issue by rptaylor** [slateci/slate-catalog#584]
When `.Values.SLATE.LocalStorage`  (side note: that's a bit of a misnomer because PVCs are not necessarily local), a PVC is used for the squid data volume, which makes up most of the storage usage. However that doesn't stop it from requesting ephemeral storage larger than the squid data volume:

https://github.com/slateci/slate-catalog/blob/master/stable/osg-frontier-squid/osg-frontier-squid/templates/deployment.yaml#L71

That means the pod requests a big emptydir , large enough for the squid data cache, but it will not use it since the cache is actually on PVC instead. This wastes disk space and makes the squid pod harder to schedule.
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-emphemeralstorage-consumption

**Comment by rptaylor** [comment]
Aside from being a misnomer, `LocalStorage`  is not SLATE-specific per se AFAICT?
Considering also https://github.com/slateci/slate-catalog/issues/582  I would suggest a new values section like this for configuring storage-related options:
```
Storage:
  usePVC: true
  storageClassName: null
  volumeName: foo
```
or maybe something like this [common pattern](https://github.com/bitnami/charts/blob/master/bitnami/kube-prometheus/values.yaml#L979)
```
persistence:
  enabled: true
  storageClass: null
  volumeName: foo
```
