### ISSUE TITLE
Built index.yaml missing all chart versions

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog#586]
* This was initially reported by Brian Lin with regards to the `osg-hosted-ce` application.
* This bug is not present in the new GitHub action-driven catalogs.

## Bug

The `index.yaml` files built by Jenkins for:
* https://jenkins.slateci.io/catalog/incubator/
* https://jenkins.slateci.io/catalog/stable/

do not contain all available chart versions. For example, in `index.yaml` for `nginx`:
```yaml
nginx:
  - apiVersion: v1
    appVersion: 1.15.9
    created: "2022-07-24T09:46:15.105994007Z"
    description: A simple nginx deployment which serves a static page
    digest: 2fbcb560c62b94ba34962297acf423c0c5aba06f4d1b00cba0c0628368f8c94e
    name: nginx
    urls:
    - nginx-1.2.0.tgz
    version: 1.2.0
```
This results in:
```shell
$ slate app versions nginx
Fetching application versions...
...
1.2.0
```
despite `nginx` versions all the way back to `1.0.0` being available on https://jenkins.slateci.io/catalog/stable/.

## Proposed Solution

Update `CMakeLists.txt` used by Jenkins to include all available versions on the pages linked above in the built `index.yaml` files.
