### ISSUE TITLE
Hosted CE should have associated network policy

### ISSUE THREAD

**Issue by bbockelm** [slateci/slate-catalog#604]
Can we add a network policy for the hosted CE?  Particularly for IPv6 environments where the pod IP is a public IP, I like to have applications explicitly declare what network connectivity they need.

Even something like this would suffice:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ template "osg-hosted-ce.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "osg-hosted-ce.name" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 9619
  egress:
  - {}
```
